name: Test and Publish

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test & publish
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        machines: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Write prod key from base64
        env:
          AUTH: ${{ secrets.PROD_SERVICE_ACCOUNT_BASE64 }}
        run: |
          echo "$AUTH" | base64 --decode > /home/runner/work/NC-back/NC-back/nc-challenge.json

      - name: Build Project && tests
        run: npm install && npm run test && npm run build
        env:
          CI: true
          PORT: 3000
          MAIN_DATABASE_TYPE: firebase
          AUTH_USE_FIREBASE: true
          DATABASE_FIREBASE_NAME: nc-challenge
          DATABASE_FIREBASE_SERVICE_ACCOUNT_PATH: ./nc-challenge.json

      - name: Deploy Production BACKEND
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: nc-challenge
          APPLICATION_CREDENTIALS: ${{ secrets.PROD_SERVICE_ACCOUNT_BASE64 }}
        with:
          args: app deploy app.yaml
